[build]
  command = "npm run build && npm run export"
  publish = "out"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' *.typekit.net 'unsafe-inline'; img-src https://*; media-src https://*;"