name: Release
on:
  push:
    branches:
      - releases/v2

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - run: npm install

      - name: build app
        run: npm run build
        env:
          CONTENTFUL_SPACE_ID: '${{ secrets.CONTENTFUL_SPACE_ID }}'
          CONTENTFUL_ACCESS_TOKEN: '${{ secrets.CONTENTFUL_ACCESS_TOKEN }}'

      - name: export app
        run: npm run export

      - name: copy netlify config
        run: cp netlify.toml out/

      - name: deploy to branch
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: deploy
          FOLDER: out
