name: Release
on:
  push:
    branches:
      - releases/v2

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - run: npm install

      - name: build app
        run: npm run build

      - name: export app
        run: npm run export

      - name: copy netlify config
        run: cp netlify.toml out/

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=out --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
